name: Legendary Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  legendary-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate random number and log to file
      id: random_number
      run: |
        RANDOM_NUMBER=$(( RANDOM ))
        echo "Random number: $RANDOM_NUMBER at $(date)" >> random_numbers.txt
        echo "::set-output name=random_number::$RANDOM_NUMBER"
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add random_numbers.txt
        git commit -m "Logged random number $RANDOM_NUMBER - This number is so cool, it can make ice jealous!"

    - name: Generate random string
      run: |
        RANDOM_STRING=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
        echo "Random string: $RANDOM_STRING at $(date)" >> random_strings.txt
        git add random_strings.txt
        git commit -m "Logged random string $RANDOM_STRING - This string is so random, even a cat couldn't predict it!"

    - name: Push changes
      run: |
        git push

    - name: Install mailutils
      run: sudo apt-get install -y mailutils

    - name: Send notification
      run: |
        echo "Random number ${{ steps.random_number.outputs.random_number }} and string $RANDOM_STRING have been logged. It's so legendary, even unicorns are impressed!" | mail -s "Legendary Log Notification" you@example.com

    - name: Fetch a random joke
      run: |
        sudo apt-get install -y jq
        JOKE=$(curl -s https://official-joke-api.appspot.com/jokes/random | jq -r '.setup + " - " + .punchline')
        echo "Random joke: $JOKE at $(date)" >> jokes.txt
        git add jokes.txt
        git commit -m "Logged random joke - $JOKE"

    - name: Install ImageMagick and fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick fonts-dejavu
        sudo fc-cache -f -v

    - name: Generate meme
      run: |
        MEME_TEXT="Legendary Automation!"
        FONT_SIZE=$((RANDOM % 30 + 60))  # Random font size between 60 and 90
        COLOR=$(printf '#%06X\n' $((RANDOM % 16777215)))  # Random color
        convert -size 800x200 xc:white -font DejaVu-Sans -pointsize $FONT_SIZE -fill "$COLOR" -draw "text 10,100 '$MEME_TEXT'" meme.png
        echo "Meme generated at $(date)" >> memes.txt
        git add meme.png memes.txt
        git commit -m "Generated meme - This meme is so legendary, even Chuck Norris approves!"
        git push

    - name: Post to Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Random number: ${{ steps.random_number.outputs.random_number }} and random string: $RANDOM_STRING. Also, here is a joke for you: $JOKE"}' $SLACK_WEBHOOK_URL

    - name: Create issue if random number is above threshold
      if: ${{ steps.random_number.outputs.random_number > 50000 }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'High Random Number Alert',
            body: `A high random number ${{ steps.random_number.outputs.random_number }} was generated. It's so high, even the sky is jealous!`
          })

    - name: Fetch and log a random quote
      run: |
        QUOTE=$(curl -s https://api.quotable.io/random | jq -r '.content + " - " + .author')
        echo "Random quote: $QUOTE at $(date)" >> quotes.txt
        git add quotes.txt
        git commit -m "Logged random quote - Wisdom so deep, it makes philosophers dizzy!"
        git push

    - name: Generate a random fact
      run: |
        FACT=$(curl -s "https://uselessfacts.jsph.pl/random.json?language=en" | jq -r '.text')
        echo "Random fact: $FACT at $(date)" >> facts.txt
        git add facts.txt
        git commit -m "Logged random fact - Knowledge so random, it confuses encyclopedias!"
        git push

    - name: Final push
      run: |
        git push || echo "No changes to push"
