name: Legendary Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  legendary-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update CA certificates
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo update-ca-certificates

    - name: Generate random number and log to file
      id: random_number
      run: |
        RANDOM_NUMBER=$(( RANDOM ))
        echo "Random number: $RANDOM_NUMBER at $(date)" >> random_numbers.txt
        echo "random_number=$RANDOM_NUMBER" >> $GITHUB_OUTPUT
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add random_numbers.txt
        git commit -m "Logged random number $RANDOM_NUMBER - This number is so cool, it can make ice jealous!"

    - name: Generate random string
      id: random_string
      run: |
        RANDOM_STRING=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '')
        echo "Random string: $RANDOM_STRING at $(date)" >> random_strings.txt
        echo "random_string=$RANDOM_STRING" >> $GITHUB_OUTPUT
        git add random_strings.txt
        git commit -m "Logged random string $RANDOM_STRING - This string is so random, even a cat couldn't predict it!"

    - name: Push changes
      run: |
        git push || echo "Failed to push changes"

    - name: Install mailutils
      run: sudo apt-get install -y mailutils

    - name: Send notification
      run: |
        echo "Random number ${{ steps.random_number.outputs.random_number }} and string ${{ steps.random_string.outputs.random_string }} have been logged. It's so legendary, even unicorns are impressed!" | mail -s "Legendary Log Notification" you@example.com || echo "Failed to send email"

    - name: Fetch a random joke
      id: random_joke
      run: |
        sudo apt-get install -y jq
        MAX_RETRIES=3
        RETRY_COUNT=0
        JOKE=""
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ -z "$JOKE" ]; do
          RESPONSE=$(curl -s --retry 3 --retry-delay 5 --max-time 30 https://official-joke-api.appspot.com/jokes/random || echo '{"setup": "Why did the API fail?", "punchline": "It was feeling a bit insecure!"}')
          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
            JOKE=$(echo "$RESPONSE" | jq -r '.setup + " - " + .punchline')
          else
            echo "Failed to fetch or parse joke, retrying..."
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5
          fi
        done
        
        if [ -z "$JOKE" ]; then
          JOKE="Why did the GitHub Action cross the road? To trigger the other workflow!"
        fi
        
        echo "Random joke: $JOKE at $(date)" >> jokes.txt
        echo "joke=$JOKE" >> $GITHUB_OUTPUT
        git add jokes.txt
        git commit -m "Logged random joke - $JOKE"

    - name: Install ImageMagick and fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick fonts-dejavu
        sudo fc-cache -f -v

    - name: Generate meme
      run: |
        MEME_TEXT="Legendary Automation!"
        FONT_SIZE=$((RANDOM % 30 + 60))  # Random font size between 60 and 90
        COLOR=$(printf '#%06X\n' $((RANDOM % 16777215)))  # Random color
        convert -size 800x200 xc:white -font DejaVu-Sans -pointsize $FONT_SIZE -fill "$COLOR" -draw "text 10,100 '$MEME_TEXT'" meme.png || echo "Failed to generate meme"
        echo "Meme generated at $(date)" >> memes.txt
        git add meme.png memes.txt
        git commit -m "Generated meme - This meme is so legendary, even Chuck Norris approves!"
        git push || echo "Failed to push meme"

    - name: Post to Slack
      if: env.SLACK_WEBHOOK_URL != ''
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        if [ -n "$SLACK_WEBHOOK_URL" ]; then
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Random number: ${{ steps.random_number.outputs.random_number }} and random string: ${{ steps.random_string.outputs.random_string }}. Also, here is a joke for you: ${{ steps.random_joke.outputs.joke }}\"}" $SLACK_WEBHOOK_URL || echo "Failed to post to Slack"
        else
          echo "Skipping Slack notification as SLACK_WEBHOOK_URL is not set"
        fi

    - name: Create issue if random number is above threshold
      if: ${{ steps.random_number.outputs.random_number > 50000 }}
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'High Random Number Alert',
            body: `A high random number ${{ steps.random_number.outputs.random_number }} was generated. It's so high, even the sky is jealous!`
          }).catch(error => {
            console.error('Failed to create issue:', error);
          });

    - name: Fetch and log a random quote
      run: |
        MAX_RETRIES=3
        RETRY_COUNT=0
        QUOTE=""
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ -z "$QUOTE" ]; do
          RESPONSE=$(curl -s --retry 3 --retry-delay 5 --max-time 30 https://api.quotable.io/random || echo '{"content": "Automation is the art of making processes work for you", "author": "Unknown"}')
          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
            QUOTE=$(echo "$RESPONSE" | jq -r '.content + " - " + .author')
          else
            echo "Failed to fetch or parse quote, retrying..."
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5
          fi
        done
        
        if [ -z "$QUOTE" ]; then
          QUOTE="Automation is the art of making processes work for you - Unknown"
        fi
        
        echo "Random quote: $QUOTE at $(date)" >> quotes.txt
        git add quotes.txt
        git commit -m "Logged random quote - Wisdom so deep, it makes philosophers dizzy!"
        git push || echo "Failed to push quote"

    - name: Generate a random fact
      run: |
        MAX_RETRIES=3
        RETRY_COUNT=0
        FACT=""
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ -z "$FACT" ]; do
          RESPONSE=$(curl -s --retry 3 --retry-delay 5 --max-time 30 "https://uselessfacts.jsph.pl/random.json?language=en" || echo '{"text": "GitHub Actions can handle API failures gracefully!"}')
          if echo "$RESPONSE" | jq -e . >/dev/null 2>&1; then
            FACT=$(echo "$RESPONSE" | jq -r '.text')
          else
            echo "Failed to fetch or parse fact, retrying..."
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 5
          fi
        done
        
        if [ -z "$FACT" ]; then
          FACT="Did you know? Sometimes, even random facts can be elusive!"
        fi
        
        echo "Random fact: $FACT at $(date)" >> facts.txt
        git add facts.txt
        git commit -m "Logged random fact - Knowledge so random, it confuses encyclopedias!"
        git push || echo "Failed to push fact"

    - name: Final push
      run: |
        git push || echo "No changes to push"
